name: Run
on: 
  workflow_dispatch:
    inputs:
      params:
        required: false
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v5
      - name: Setup git-blame-someone-else
        run: |
          git clone https://github.com/jayphelps/git-blame-someone-else.git
          cd git-blame-someone-else
          make install
      - name: run
        run: |
         git config --local user.email "actions@github.com"
         git config --local user.name "GitHub Actions"
         run() {
          	local command=""
          	local arg=""
          	for arg in "$@"; do
           		if [[ $arg != "--" ]]; then
           			command+="$arg "
          		else
          			eval "$command"
          			command=""
          		fi
          	done
          	eval "$command"
         }
         run ${{ github.event.inputs.params }}	
